name: Creacion de workflow para CI

# b. Configurar los triggers
on:
  push:
    branches: [ main ]

# c. Configurar los trabajos a realizar
jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest

    # d. Configurar dentro de los trabajos los pasos a ejecutarse
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar las dependencias
        run: npm install

      - name: Ejecutar linter
        run: npm run lint

      - name: Ejecutar pruebas
        run: npm test

      # Paso configurado para provocar un error deliberadamente
      - name: Provocar error intencional
        run: |
          echo "Este paso provocara un error en la ejecucion del CI workflow"
          exit 1
